/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from "@metaplex-foundation/beet";
import * as web3 from "@solana/web3.js";
import { FinishGameArgs, finishGameArgsBeet } from "../types/FinishGameArgs";

/**
 * @category Instructions
 * @category FinishGame
 * @category generated
 */
export type FinishGameInstructionArgs = {
  args: FinishGameArgs;
};
/**
 * @category Instructions
 * @category FinishGame
 * @category generated
 */
export const finishGameStruct = new beet.BeetArgsStruct<
  FinishGameInstructionArgs & {
    instructionDiscriminator: number[] /* size: 8 */;
  }
>(
  [
    ["instructionDiscriminator", beet.uniformFixedSizeArray(beet.u8, 8)],
    ["args", finishGameArgsBeet],
  ],
  "FinishGameInstructionArgs",
);
/**
 * Accounts required by the _finishGame_ instruction
 *
 * @property [_writable_, **signer**] signer
 * @property [] crank
 * @property [_writable_] game
 * @property [] winner
 * @property [] playersActions
 * @category Instructions
 * @category FinishGame
 * @category generated
 */
export type FinishGameInstructionAccounts = {
  signer: web3.PublicKey;
  crank: web3.PublicKey;
  game: web3.PublicKey;
  winner: web3.PublicKey;
  playersActions: web3.PublicKey;
  systemProgram?: web3.PublicKey;
  rent?: web3.PublicKey;
  anchorRemainingAccounts?: web3.AccountMeta[];
};

export const finishGameInstructionDiscriminator = [
  168, 120, 86, 113, 64, 116, 2, 146,
];

/**
 * Creates a _FinishGame_ instruction.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @param args to provide as instruction data to the program
 *
 * @category Instructions
 * @category FinishGame
 * @category generated
 */
export function createFinishGameInstruction(
  accounts: FinishGameInstructionAccounts,
  args: FinishGameInstructionArgs,
  programId = new web3.PublicKey(
    "2yKYJeX7NDF6gSHANJqnxHuAuHuBx5Qf3s9oAmMpWzxh",
  ),
) {
  const [data] = finishGameStruct.serialize({
    instructionDiscriminator: finishGameInstructionDiscriminator,
    ...args,
  });
  const keys: web3.AccountMeta[] = [
    {
      pubkey: accounts.signer,
      isWritable: true,
      isSigner: true,
    },
    {
      pubkey: accounts.crank,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.game,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.winner,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.playersActions,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.systemProgram ?? web3.SystemProgram.programId,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.rent ?? web3.SYSVAR_RENT_PUBKEY,
      isWritable: false,
      isSigner: false,
    },
  ];

  if (accounts.anchorRemainingAccounts != null) {
    for (const acc of accounts.anchorRemainingAccounts) {
      keys.push(acc);
    }
  }

  const ix = new web3.TransactionInstruction({
    programId,
    keys,
    data,
  });
  return ix;
}
