/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from "@metaplex-foundation/beet";
import * as web3 from "@solana/web3.js";

/**
 * @category Instructions
 * @category InitCrank
 * @category generated
 */
export const initCrankStruct = new beet.BeetArgsStruct<{
  instructionDiscriminator: number[] /* size: 8 */;
}>(
  [["instructionDiscriminator", beet.uniformFixedSizeArray(beet.u8, 8)]],
  "InitCrankInstructionArgs",
);
/**
 * Accounts required by the _initCrank_ instruction
 *
 * @property [_writable_, **signer**] signer
 * @property [] crankSigner
 * @property [_writable_] crank
 * @category Instructions
 * @category InitCrank
 * @category generated
 */
export type InitCrankInstructionAccounts = {
  signer: web3.PublicKey;
  crankSigner: web3.PublicKey;
  crank: web3.PublicKey;
  systemProgram?: web3.PublicKey;
  rent?: web3.PublicKey;
  anchorRemainingAccounts?: web3.AccountMeta[];
};

export const initCrankInstructionDiscriminator = [
  175, 166, 133, 188, 47, 135, 191, 65,
];

/**
 * Creates a _InitCrank_ instruction.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @category Instructions
 * @category InitCrank
 * @category generated
 */
export function createInitCrankInstruction(
  accounts: InitCrankInstructionAccounts,
  programId = new web3.PublicKey(
    "2yKYJeX7NDF6gSHANJqnxHuAuHuBx5Qf3s9oAmMpWzxh",
  ),
) {
  const [data] = initCrankStruct.serialize({
    instructionDiscriminator: initCrankInstructionDiscriminator,
  });
  const keys: web3.AccountMeta[] = [
    {
      pubkey: accounts.signer,
      isWritable: true,
      isSigner: true,
    },
    {
      pubkey: accounts.crankSigner,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.crank,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.systemProgram ?? web3.SystemProgram.programId,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.rent ?? web3.SYSVAR_RENT_PUBKEY,
      isWritable: false,
      isSigner: false,
    },
  ];

  if (accounts.anchorRemainingAccounts != null) {
    for (const acc of accounts.anchorRemainingAccounts) {
      keys.push(acc);
    }
  }

  const ix = new web3.TransactionInstruction({
    programId,
    keys,
    data,
  });
  return ix;
}
