/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as splToken from "@solana/spl-token";
import * as beet from "@metaplex-foundation/beet";
import * as web3 from "@solana/web3.js";
import {
  PlayerProfileDepositArgs,
  playerProfileDepositArgsBeet,
} from "../types/PlayerProfileDepositArgs";

/**
 * @category Instructions
 * @category PlayerProfileDeposit
 * @category generated
 */
export type PlayerProfileDepositInstructionArgs = {
  args: PlayerProfileDepositArgs;
};
/**
 * @category Instructions
 * @category PlayerProfileDeposit
 * @category generated
 */
export const playerProfileDepositStruct = new beet.BeetArgsStruct<
  PlayerProfileDepositInstructionArgs & {
    instructionDiscriminator: number[] /* size: 8 */;
  }
>(
  [
    ["instructionDiscriminator", beet.uniformFixedSizeArray(beet.u8, 8)],
    ["args", playerProfileDepositArgsBeet],
  ],
  "PlayerProfileDepositInstructionArgs",
);
/**
 * Accounts required by the _playerProfileDeposit_ instruction
 *
 * @property [_writable_, **signer**] signer
 * @property [_writable_] signerTokenAccount
 * @property [_writable_] playerProfile
 * @property [_writable_] playerTokenAccount
 * @property [] mint
 * @property [] associatedTokenProgram
 * @category Instructions
 * @category PlayerProfileDeposit
 * @category generated
 */
export type PlayerProfileDepositInstructionAccounts = {
  signer: web3.PublicKey;
  signerTokenAccount: web3.PublicKey;
  playerProfile: web3.PublicKey;
  playerTokenAccount: web3.PublicKey;
  mint: web3.PublicKey;
  systemProgram?: web3.PublicKey;
  tokenProgram?: web3.PublicKey;
  associatedTokenProgram: web3.PublicKey;
  rent?: web3.PublicKey;
  anchorRemainingAccounts?: web3.AccountMeta[];
};

export const playerProfileDepositInstructionDiscriminator = [
  16, 63, 133, 120, 65, 103, 226, 248,
];

/**
 * Creates a _PlayerProfileDeposit_ instruction.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @param args to provide as instruction data to the program
 *
 * @category Instructions
 * @category PlayerProfileDeposit
 * @category generated
 */
export function createPlayerProfileDepositInstruction(
  accounts: PlayerProfileDepositInstructionAccounts,
  args: PlayerProfileDepositInstructionArgs,
  programId = new web3.PublicKey(
    "2yKYJeX7NDF6gSHANJqnxHuAuHuBx5Qf3s9oAmMpWzxh",
  ),
) {
  const [data] = playerProfileDepositStruct.serialize({
    instructionDiscriminator: playerProfileDepositInstructionDiscriminator,
    ...args,
  });
  const keys: web3.AccountMeta[] = [
    {
      pubkey: accounts.signer,
      isWritable: true,
      isSigner: true,
    },
    {
      pubkey: accounts.signerTokenAccount,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.playerProfile,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.playerTokenAccount,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.mint,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.systemProgram ?? web3.SystemProgram.programId,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.tokenProgram ?? splToken.TOKEN_PROGRAM_ID,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.associatedTokenProgram,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.rent ?? web3.SYSVAR_RENT_PUBKEY,
      isWritable: false,
      isSigner: false,
    },
  ];

  if (accounts.anchorRemainingAccounts != null) {
    for (const acc of accounts.anchorRemainingAccounts) {
      keys.push(acc);
    }
  }

  const ix = new web3.TransactionInstruction({
    programId,
    keys,
    data,
  });
  return ix;
}
