application:
  port: 8000
  base_url: http://127.0.0.1
database:
  host: 127.0.0.1
  port: 5555
  username: "postgres"
  password: "password"
  name: "brain-wars"
  require_ssl: false
constants:
  min_game_length: 3
  max_game_length: 45
  game_entries: [10.0, 20.0]
  countdown_for_others_to_join: 5000
  worker_interval: 1000
  eth_rpc: https://dawn-evocative-haze.discover.quiknode.pro/13f8d0312edcd65ea706b693e4f52dae14bf538b/
  eth_scan_api_key: 37X7TJFTZMQ6MC4M97DPGQ9ZXCTE8HG9RE
  eth_moralis_api_key: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJub25jZSI6IjRiYzJmNTI0LTU5ZTYtNGZmNy05MjdmLTdiOTJkNzI5OTUxOCIsIm9yZ0lkIjoiMzUyOTU1IiwidXNlcklkIjoiMzYyNzcwIiwidHlwZUlkIjoiY2FiNjNlMGUtZGY3YS00NjgyLWEzOGUtNzJhMWJkYWEwOWUzIiwidHlwZSI6IlBST0pFQ1QiLCJpYXQiOjE2OTE5NTgyNDksImV4cCI6NDg0NzcxODI0OX0.YNXNp9u37qv3XHe3267aCihGpDeBPfkSJM_rooqsKZA
